/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnotherPageRouteImport } from './routes/anotherPage'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FomsRouteRouteImport } from './routes/foms/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FomsIndexRouteImport } from './routes/foms/index'
import { Route as FomsCreateRouteImport } from './routes/foms/create'
import { Route as FomsRequestIdRouteImport } from './routes/foms/$requestId'

const AnotherPageRoute = AnotherPageRouteImport.update({
  id: '/anotherPage',
  path: '/anotherPage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FomsRouteRoute = FomsRouteRouteImport.update({
  id: '/foms',
  path: '/foms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FomsIndexRoute = FomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FomsRouteRoute,
} as any)
const FomsCreateRoute = FomsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => FomsRouteRoute,
} as any)
const FomsRequestIdRoute = FomsRequestIdRouteImport.update({
  id: '/$requestId',
  path: '/$requestId',
  getParentRoute: () => FomsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/foms': typeof FomsRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/anotherPage': typeof AnotherPageRoute
  '/foms/$requestId': typeof FomsRequestIdRoute
  '/foms/create': typeof FomsCreateRoute
  '/foms/': typeof FomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anotherPage': typeof AnotherPageRoute
  '/foms/$requestId': typeof FomsRequestIdRoute
  '/foms/create': typeof FomsCreateRoute
  '/foms': typeof FomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/foms': typeof FomsRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/anotherPage': typeof AnotherPageRoute
  '/foms/$requestId': typeof FomsRequestIdRoute
  '/foms/create': typeof FomsCreateRoute
  '/foms/': typeof FomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/foms'
    | '/admin'
    | '/anotherPage'
    | '/foms/$requestId'
    | '/foms/create'
    | '/foms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/anotherPage'
    | '/foms/$requestId'
    | '/foms/create'
    | '/foms'
  id:
    | '__root__'
    | '/'
    | '/foms'
    | '/admin'
    | '/anotherPage'
    | '/foms/$requestId'
    | '/foms/create'
    | '/foms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FomsRouteRoute: typeof FomsRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AnotherPageRoute: typeof AnotherPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/anotherPage': {
      id: '/anotherPage'
      path: '/anotherPage'
      fullPath: '/anotherPage'
      preLoaderRoute: typeof AnotherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foms': {
      id: '/foms'
      path: '/foms'
      fullPath: '/foms'
      preLoaderRoute: typeof FomsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foms/': {
      id: '/foms/'
      path: '/'
      fullPath: '/foms/'
      preLoaderRoute: typeof FomsIndexRouteImport
      parentRoute: typeof FomsRouteRoute
    }
    '/foms/create': {
      id: '/foms/create'
      path: '/create'
      fullPath: '/foms/create'
      preLoaderRoute: typeof FomsCreateRouteImport
      parentRoute: typeof FomsRouteRoute
    }
    '/foms/$requestId': {
      id: '/foms/$requestId'
      path: '/$requestId'
      fullPath: '/foms/$requestId'
      preLoaderRoute: typeof FomsRequestIdRouteImport
      parentRoute: typeof FomsRouteRoute
    }
  }
}

interface FomsRouteRouteChildren {
  FomsRequestIdRoute: typeof FomsRequestIdRoute
  FomsCreateRoute: typeof FomsCreateRoute
  FomsIndexRoute: typeof FomsIndexRoute
}

const FomsRouteRouteChildren: FomsRouteRouteChildren = {
  FomsRequestIdRoute: FomsRequestIdRoute,
  FomsCreateRoute: FomsCreateRoute,
  FomsIndexRoute: FomsIndexRoute,
}

const FomsRouteRouteWithChildren = FomsRouteRoute._addFileChildren(
  FomsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FomsRouteRoute: FomsRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AnotherPageRoute: AnotherPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
